export type TruthOrDarePromptType = "Truth" | "Dare";

export const truthPrompts = [
  "What's the most adventurous place you've ever hooked up?",
  "Have you ever had a friends-with-benefits situation? How did it end?",
  "What's your biggest fantasy you've never told anyone?",
  "Have you ever been attracted to someone in this room?",
  "What body part do you find most attractive on a partner?",
  "What's something you secretly want someone to do to you?",
  "Have you ever slept with more than one person in the same day?",
  "What's the most turned on you've ever been in public?",
  "Have you ever role-played? What was the scenario?",
  "What's your type in bed — dominant, submissive, or switch?",
  "Have you ever had a one-night stand with someone whose name you never learned?",
  "What instantly makes you weak in the knees?",
  "Have you ever sexted the wrong person? What happened?",
  "What's the naughtiest thing you've done at work?",
  "Have you ever faked it — and who with?",
  "What's the most desperate you've ever been for someone's touch?",
  "Describe your ideal partner in bed — body, energy, everything.",
  "What's a sexual deal-breaker for you?",
  "Have you ever been caught in a compromising situation?",
  "What's the one thing guaranteed to drive you absolutely wild?",
  "Have you ever been so attracted to someone you couldn't think straight?",
  "What's the most embarrassing place you've ever been in the mood?",
  "Have you ever hooked up with someone you probably shouldn't have?",
  "What's your biggest unfulfilled fantasy?",
  "What's something sexual you'd never admit to your family?",
  "Have you ever done anything naughty in a semi-public place?",
  "What's the most number of people you've been involved with in one month?",
  "What's a sexual experience you'd never repeat, and why?",
  "Who in this room would you most want to spend a night with?",
  "What's the dirtiest thought you've had about someone in this room tonight?",
];

export const darePrompts = [
  "Give a 60-second lap dance to the person on your left.",
  "Whisper your dirtiest fantasy to the person sitting next to you.",
  "Let someone trace their finger slowly up your arm for 30 seconds.",
  "Maintain intense eye contact with someone while slowly biting your lip for 45 seconds.",
  "Give a 2-minute back massage as seductively as possible.",
  "Text your last ex 'I miss you' and show everyone the reply.",
  "Let the group read your last 10 messages to your most recent flirt.",
  "Do a slow, seductive dance for 60 seconds.",
  "Let someone run an ice cube along your collarbone.",
  "Sit on someone's lap for the next 3 rounds.",
  "Give the most convincing come-hither look to someone across the room.",
  "Describe out loud what you'd do to the most attractive person in the room.",
  "Let someone blindfold you and guess who touches your hand.",
  "Call someone in your contacts and flirt with them for 30 seconds.",
  "Let someone write something on your body with a marker.",
  "Re-enact your most embarrassing intimate moment.",
  "Send a flirty voice note to someone in your contacts right now.",
  "Demonstrate your best kiss face on someone's hand.",
  "Let someone feed you something as seductively as possible.",
  "Describe in detail what you'd do on a perfect intimate night.",
  "Remove one item of clothing — it stays off for 3 rounds.",
  "Take a body shot off the person of the group's choosing.",
  "Let someone give you a hickey somewhere visible.",
  "Read your most flirtatious text exchange out loud to the group.",
  "Let the group pick your phone wallpaper for the rest of the night.",
  "Act out what you look like at your absolute best during intimacy — no speaking.",
  "Whisper exactly what you want done to you to the person on your right.",
  "Let someone draw on your thigh with a marker.",
  "Make eye contact and do your best seductive look for 30 seconds without laughing.",
  "Describe your perfect fantasy scenario in explicit detail to the group.",
];